# Generated by Django 4.0.5 on 2022-06-10 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_info',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_photo',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_url',
            new_name='url',
        ),
    ]
