# Generated by Django 4.0.5 on 2022-06-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_remove_commentsoncomment_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo_users', verbose_name='Photo'),
        ),
    ]
