# Generated by Django 4.0.5 on 2022-06-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_userprofile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
