# Generated by Django 4.0.5 on 2022-06-13 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_article_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time_create',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: 06751102sd00', regex='^(067|096|097|098|050|066|095|099|063|073|093)\\d{7}$')]),
        ),
    ]
