# Generated by Django 4.0.5 on 2022-06-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_comment_time_create_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='time_create',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
