# Generated by Django 4.0.5 on 2022-06-10 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_year_public',
            new_name='date_public',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_genre',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_available',
            new_name='is_available',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='userprof',
            old_name='user_info',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='userprof',
            old_name='user_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='userprof',
            old_name='user_photo',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='userprof',
            old_name='user_url',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='userprof',
            old_name='user_prof',
            new_name='user',
        ),
    ]
