# Generated by Django 4.0.5 on 2022-06-10 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_rename_book_author_book_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprof',
            name='user',
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.genre'),
        ),
        migrations.AlterField(
            model_name='phoneuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.userprof'),
        ),
    ]
