# Generated by Django 4.0.5 on 2022-06-10 09:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=100, verbose_name='Title')),
                ('article_content', models.TextField(blank=True, verbose_name='Content')),
                ('article_time_create', models.DateTimeField(auto_now_add=True)),
                ('article_time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_time_create', models.DateTimeField(auto_now_add=True)),
                ('comment_time_update', models.DateTimeField(auto_now=True)),
                ('comment_body', models.CharField(max_length=255)),
                ('comment_active', models.BooleanField(default=True)),
                ('comment_article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.article')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_photo', models.ImageField(null=True, upload_to='photo_users', verbose_name='Photo')),
                ('user_url', models.URLField()),
                ('user_info', models.CharField(default='Information is absent', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: 0675110200', regex='^(067|096|097|098|050|066|095|099|063|073|093)\\d{7}$')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='blog_app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LikeDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.SmallIntegerField(choices=[(-1, 'Dislake'), (1, 'Like')], default=1)),
                ('like_time_create', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CommentsOnComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coc_time_create', models.DateTimeField(auto_now_add=True)),
                ('coc_time_update', models.DateTimeField(auto_now=True)),
                ('coc_body', models.CharField(max_length=255)),
                ('coc_active', models.BooleanField(default=True)),
                ('coc_author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.userprofile')),
                ('coc_comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.comments')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.userprofile'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='blog_app.userprofile'),
        ),
    ]
