# Generated by Django 4.0.5 on 2022-06-10 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_rename_user_info_userprofile_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_time_create',
            new_name='time_create',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_time_update',
            new_name='time_update',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='comment_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='comment_article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='comment_author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='comment_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='comment_time_create',
            new_name='time_create',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='comment_time_update',
            new_name='time_update',
        ),
        migrations.RenameField(
            model_name='commentsoncomment',
            old_name='coc_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='commentsoncomment',
            old_name='coc_author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='commentsoncomment',
            old_name='coc_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='commentsoncomment',
            old_name='coc_comment_id',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='commentsoncomment',
            old_name='coc_time_create',
            new_name='time_create',
        ),
        migrations.RenameField(
            model_name='commentsoncomment',
            old_name='coc_time_update',
            new_name='time_update',
        ),
        migrations.RenameField(
            model_name='likedislike',
            old_name='like_time_create',
            new_name='time_create',
        ),
    ]
